-- Seed data for the romantic birthday app.
-- Safe to re-run: uses ON CONFLICT upserts for tables with unique keys.

-- =========================
-- Journey (Daily Surprises)
-- =========================
INSERT INTO daily_surprises (day_number, type, title, content, media_url)
VALUES
  (1, 'letter', 'A tiny beginning', '💌✨ Hey love. If you ever doubt yourself today, remember this: you have a way of making ordinary moments feel like home. 🏡💗 I’m proud of you for showing up, for trying, for being you — even when you feel tired. 🌙🫶 Take a slow breath for me 😮‍💨 and keep going gently.', NULL),
  (2, 'letter', 'I notice you', '👀💞 I notice you — the way you care softly, the way you try without needing applause, the way you keep your heart gentle. 🌸🥹 That kind of love is rare. And you’re rare. ✨🫶 If nobody told you today: you’re doing amazing, and I’m grateful I get to love you. 💗', NULL),
  (3, 'letter', 'For your smile', '☀️😊 Your smile doesn’t just brighten a room — it changes the weather inside me. 🌤️💓 When you smile, my mind gets quiet and my heart gets loud. 🥹💗 I hope you smile today, even if it’s small. And if you don’t, that’s okay — I’ll hold the day gently for you. 🫶🌙', NULL),
  (4, 'letter', 'The calm you bring', '🌊🫶 When life gets loud, you are the quiet I want. The safe I choose. The peace my heart recognizes. 🕊️💗 I love how you make things feel softer just by being near. ✨ If today is chaos, come back to me in tiny ways — a message, a thought, a breath. 📩😮‍💨', NULL),
  (5, 'letter', 'A promise', '💍💗 I promise to keep learning you — your dreams, your fears, your favorite little joys. 🌸🧠 I promise to love you better as I learn, not louder… just deeper. 🌙✨ And I promise to never make you feel like your heart is “too much.” It’s beautiful. It’s home. 🏡🫶', NULL),
  (6, 'letter', 'Your softness is strength', '🛡️🌸 Your gentleness isn’t weakness — it’s strength with grace. ✨💗 You’re soft, but you’re not fragile. You care, but you don’t break. 🫶 If the world ever tries to harden you, remember: your softness is part of your magic. 🪄🌙', NULL),
  (7, 'letter', 'One thing I adore', '🥰🎀 I adore how you can be both serious and silly. How you can be deep and playful. 🌊✨ You’re poetry and chaos in the sweetest balance, and it makes me smile every time. 😊💗 Never shrink the parts of you that feel alive. 🫶', NULL),
  (8, 'letter', 'A warm thought', '🧸💞 If I could, I’d wrap you in a blanket made from every good memory we’ve made and every good thing still coming. 🧵✨ I’d keep you warm from doubt, stress, and sadness. 🌙🫶 Until then, keep this: you’re loved, you’re safe, you’re mine. 💗', NULL),
  (9, 'letter', 'You are my favorite habit', '💭💗 Thinking about you is my favorite habit. Loving you is my favorite decision. 🫶✨ I love the tiny ways you live in my day — in songs, in random moments, in the quiet. 🎶🌙 If you ever wonder if you matter to me… you do. Constantly. 💞', NULL),
  (10, 'letter', 'The way you try', '🌟🫶 Even on hard days, you keep trying. That’s one of the most beautiful things about you. 🥹💗 I see it. I admire it. I’m proud of it. 🏆✨ Please don’t measure yourself by your tired moments — measure yourself by your heart. It’s huge. 💞', NULL),
  (11, 'letter', 'I’d choose you', '🫶💍 In a room full of chances, I’d still choose you. Again. And again. ✨💗 Not because it’s easy — because it’s real. Because your heart feels like something I want to keep safe. 🧸🌙 I’m grateful for you. Always.', NULL),
  (12, 'letter', 'Your laugh', '😂💗 Your laugh is one of my favorite sounds — it feels like sunshine with a heartbeat. ☀️💓 I hope life gives you reasons to laugh today, and if it doesn’t… I’ll try to be one. 🫶✨ You deserve joy that finds you easily. 🌈', NULL),
  (13, 'letter', 'A small reminder', '🚰💞 Drink water. 😮‍💨 Take a breath. 🧸 Be gentle with yourself. 🌙✨ You don’t have to do everything perfectly to be lovable — you’re already loved. 🫶💗 I’m cheering for you quietly in the background like your personal lucky charm. 🍀', NULL),
  (14, 'letter', 'You make things softer', '🫧💗 You have this gift: you make people feel less alone. You made me feel less alone. 🌙🫶 That matters more than you know. ✨ Today, if you feel overwhelmed, remember you’re not carrying life by yourself — you have me. Always. 🧸', NULL),
  (15, 'letter', 'My favorite timeline', '⏳💞 My favorite timeline is the one where I get to love you openly, patiently, and on purpose. 💗✨ Where your smile becomes my routine and your peace becomes our habit. 🏡🌙 I want to build a life that feels soft to live in — with you. 🫶', NULL),
  (16, 'letter', 'A love note with courage', '🫶🔥 If you feel scared today, take my hand anyway. We can be brave together. 🌙✨ You don’t have to be fearless — just willing. And you already are. 💗 I believe in you more than you know. 🥹', NULL),
  (17, 'letter', 'The future sounds like you', '🔮💗 When I think of the future, it sounds like your name said gently. 🌙✨ It feels like calm mornings, soft nights, and a love that keeps choosing. 🏡🫶 If the future ever feels uncertain, remember: you’re my favorite certainty. 💞', NULL),
  (18, 'letter', 'Your heart is a place', '🏡💗 Your heart is a place I want to treat with care — not just today, always. 🫶✨ I want to be the person who brings you comfort, not confusion. 🌙🥹 You deserve love that feels safe, steady, and kind. 💞', NULL),
  (19, 'letter', 'You are not “too much”', '🛑💗 You are not “too much.” Not too emotional. Not too sensitive. Not too intense. 🌙✨ You are a blessing — and anyone who loves you properly will understand that your heart is a gift. 🫶🥹 I love you exactly as you are. 💞', NULL),
  (20, 'letter', 'Thank you', '🙏💗 Thank you for existing exactly as you are. Thank you for letting me love you. Thank you for being my favorite. 🫶✨ If I could put my gratitude in your hands, it would look like flowers, warm tea, and a long hug. 🌸🫖🫂', NULL),
  (21, 'letter', 'A gentle dare', '💗✨ Today, let yourself receive love without questioning it. 🫶🌙 Start with mine. 💌 If your mind tries to argue, just breathe and say: “I deserve softness.” 😮‍💨🧸 Because you do. Always.', NULL),
  (22, 'letter', 'Your magic', '🪄💗 Your magic is in the details: the way you listen, the way you remember, the way you show up. ✨🫶 It’s not loud — it’s real. 🌙🥹 I’m still amazed by you, even in the simplest moments. 💞', NULL),
  (23, 'letter', 'Even on tired days', '😴💗 Even on tired days, you are worthy of tenderness. 🧸✨ You don’t have to “earn” rest or affection. 🌙🫶 I hope you treat yourself like someone you love today — gently, patiently, kindly. 💞', NULL),
  (24, 'letter', 'My favorite place', '🫶🏡 My favorite place is anywhere your hand fits in mine. ✨💗 It’s not about where we are — it’s about who I’m with. 🌙😊 I want more moments that feel like that: simple, close, and safe. 🧸', NULL),
  (25, 'letter', 'A soft confession', '🥹💗 Sometimes I catch myself smiling for no reason… then I realize I was thinking about you. 😊✨ You live in my thoughts like a song I don’t get tired of. 🎶🌙 If you ever feel far, remember: you’re still with me. Always. 🫶', NULL),
  (26, 'letter', 'You deserve ease', '🍃💗 I hope life meets you gently today. And if it doesn’t, I’ll meet you gently anyway. 🫶🌙 You deserve ease, softness, and love that doesn’t feel heavy. ✨🧸 I want to be a safe place, not another storm.', NULL),
  (27, 'letter', 'You are a masterpiece', '🎨💗 You are a masterpiece — not because you’re perfect, but because you’re real. ✨🫶 Your growth is beautiful. Your effort is beautiful. 🌙🥹 Don’t rush yourself. I love every version of you. 💞', NULL),
  (28, 'letter', 'I’m on your side', '🫶💗 In every version of every story, I’m on your side. Always. ✨ If the world feels unfair, if your thoughts feel loud, if people misunderstand you — I’m still here. 🌙🧸 You and me. Same team. 💞', NULL),
  (29, 'letter', 'A little sparkle', '✨💗 You bring sparkle to ordinary days. Not the fake kind — the real kind that comes from warmth and presence. 🫶😊 If today feels dull, remember you’re still bright. 🌙⭐ You don’t have to perform to shine.', NULL),
  (30, 'letter', 'How lucky I feel', '🍀💗 I feel lucky — quietly, deeply, constantly — that I get to love you. ✨🫶 I don’t take your heart for granted. 🌙🥹 If I could, I’d remind you every day: you are precious to me. 💞', NULL),
  (31, 'letter', 'Soft pride', '🏆💗 I’m proud of the person you are and the person you’re becoming. 🌸✨ I’m proud of your effort, your resilience, your softness. 🫶🌙 And I hope you’re proud too — because you’re doing better than you think. 🥹', NULL),
  (32, 'letter', 'I love your mind', '🧠💗 I love the way you think — the way you connect things, the way you notice what others miss. ✨🫶 Your mind is beautiful to me. 🌙📚 I want to listen to your thoughts forever, even the messy ones. 💞', NULL),
  (33, 'letter', 'Small comfort', '😮‍💨💗 If today feels too big, take it one breath at a time. 🫶🌙 You don’t have to solve everything at once. 🧸✨ Just take the next gentle step. I’m with you in the small moments — that’s where love lives too. 💞', NULL),
  (34, 'letter', 'Your light is real', '✨💗 You don’t have to be “on” to be loved. Not productive, not perfect, not smiling. 🌙🫶 You’re loved in your quiet, your messy, your tired too. 🧸🥹 Let yourself rest without guilt today. 💞', NULL),
  (35, 'letter', 'A gentle celebration', '🎉💗 I hope you celebrate yourself today — even if it’s just a tiny thing. 🌸✨ A small win, a soft moment, a deep breath. 🫶🌙 You deserve to feel proud of you. I’m proud of you. 🥹🏆', NULL),
  (36, 'letter', 'You’re my favorite thought', '💭💗 Sometimes I pause and just think of you. It’s like my heart stretches and relaxes at the same time. 🫶🌙 You make me feel calm and excited in one breath. 😮‍💨✨ I love you. Simply. Deeply. Always. 💞', NULL),
  (37, 'letter', 'My safe place', '🏡💗 You feel like a safe place I can return to. 🌙🫶 Thank you for being gentle with me, for letting love feel soft. ✨🧸 I want to be that safe place for you too — a home for your heart. 💞', NULL),
  (38, 'letter', 'I trust you', '🤍💗 I trust your heart. I trust your intentions. I trust the love you carry. 🫶✨ And I trust that you’ll keep growing into the life you deserve. 🌙🌱 If you ever forget your own strength, borrow my belief. 💞', NULL),
  (39, 'letter', 'Your tenderness', '🫧💗 Your tenderness is a gift. The world needs more of it. I need more of it. 🌙🫶 I love how you care in quiet ways, how you hold people gently. ✨🧸 Please don’t let life harden you. Your softness is your beauty. 💞', NULL),
  (40, 'letter', 'You deserve good mornings', '☀️💗 You deserve mornings that feel calm — warm light, soft thoughts, good news. 🫶✨ And even if your morning isn’t perfect, you still deserve kindness from yourself. 🌙🧸 I’m sending you love like a little sunrise in your pocket. 🌅💞', NULL),
  (41, 'letter', 'Your effort is love', '🫶💗 The way you try, the way you show up, the way you care — those are love languages too. ✨🌙 You don’t have to do grand gestures to be incredible. 🧸🥹 Your consistency is beautiful. Your heart is beautiful. 💞', NULL),
  (42, 'letter', 'A quiet promise', '🤍💗 I’ll keep choosing you in the small moments. In the ordinary. In the calm. 🫶✨ That’s where forever lives — not in fireworks, but in steady love. 🌙🏡 I want to be steady for you. Always. 💞', NULL),
  (43, 'letter', 'You’re enough', '🪞💗 Not “almost.” Not “when you fix this.” Not “when you’re better.” You, right now, are enough. 🫶✨ If your mind tries to argue, I’ll say it louder: you’re enough. 🌙🥹 You always have been. 💞', NULL),
  (44, 'letter', 'My favorite warmth', '🔥💗 If I could bottle one feeling, it would be the warmth I feel when you’re near. 🫶✨ It’s comfort, excitement, peace — all mixed together. 🌙😊 I hope you feel loved today in a way that makes your shoulders relax. 😮‍💨🧸', NULL),
  (45, 'letter', 'I love your honesty', '🤍💗 I love how real you are — how you don’t fake softness or strength. 🫶✨ You show up honestly, even when it’s hard. 🌙🥹 That’s rare. That’s beautiful. And I love you for it — every honest piece. 💞', NULL),
  (46, 'letter', 'You are loved loudly', '❤️‍🔥💗 If you ever can’t hear it from the world, hear it from me: you are loved. Deeply. Softly. Completely. 🫶🌙 You don’t have to prove you deserve it. ✨🧸 I love you because you’re you. That’s enough. 💞', NULL),
  (47, 'letter', 'You make time sweeter', '⏳💗 You make time feel sweeter. Slower. Like it’s okay to breathe. 😮‍💨✨ I love being in the same moment as you, even when nothing special is happening. 🫶🌙 Because with you, it always feels special. 💞', NULL),
  (48, 'letter', 'I’m grateful', '🙏💗 I’m grateful for you — your heart, your presence, your patience, your whole beautiful self. 🫶✨ Thank you for existing in my life. 🌙🥹 I don’t say it enough, but I feel it all the time: I’m lucky to love you. 💞', NULL),
  (49, 'letter', 'A little kiss in words', '💋💗 Pretend this is a kiss on your forehead — the kind that says: I’ve got you. 🫶🌙 The kind that makes you feel safe. 🧸✨ If today is tough, let this be your reminder: you’re not alone. I’m here. 💞', NULL),
  (50, 'letter', 'Still you', '💍💗 Even after everything, it’s still you. It will always be you for me. 🫶✨ I don’t love you for the perfect days only — I love you in the real days, the messy days, the quiet days. 🌙🧸 I love you. Always. 💞', NULL)
ON CONFLICT (day_number)
DO UPDATE SET
  type = EXCLUDED.type,
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  media_url = EXCLUDED.media_url;

-- ==================
-- For You (Reasons)
-- ==================
INSERT INTO reasons (unlock_day, reason_text)
VALUES
  (1, '💗 Because you make kindness look effortless.'),
  (2, '🌙 Because you’re gentle in a world that forgets to be.'),
  (3, '✨ Because your presence feels like peace.'),
  (4, '🫶 Because you love with your whole heart.'),
  (5, '🌸 Because you notice the small things—and you make them matter.'),
  (6, '🔥 Because you’re brave, even when you’re scared.'),
  (7, '☀️ Because you can turn a bad day into something softer.'),
  (8, '🎀 Because you’re thoughtful in ways people don’t always see.'),
  (9, '🌊 Because you keep going, even when it’s heavy.'),
  (10, '🧁 Because you make life sweeter just by being in it.'),
  (11, '🕊️ Because your heart is safe to hold.'),
  (12, '🌟 Because you inspire me to be better—without ever demanding it.'),
  (13, '🍯 Because you’re warm in the ways that count.'),
  (14, '💫 Because you feel like a wish that came true.'),
  (15, '🧸 Because you deserve tenderness—and I want to give it.'),
  (16, '🎶 Because your laugh is my favorite song.'),
  (17, '🍓 Because you’re soft and strong at the same time.'),
  (18, '🌷 Because you make love feel easy to believe in.'),
  (19, '🪞 Because you help me see the good in myself too.'),
  (20, '💍 Because I would choose you, again and again.'),
  (21, '🫧 Because you make heavy days feel lighter.'),
  (22, '🌈 Because you bring color back to my thoughts.'),
  (23, '🕯️ Because you’re steady, even when the world flickers.'),
  (24, '🍃 Because being with you feels like fresh air.'),
  (25, '🧠 Because your mind is beautiful to me.'),
  (26, '🤍 Because your heart is honest.'),
  (27, '🪐 Because you make my world feel bigger—in the best way.'),
  (28, '🫖 Because you know how to comfort without forcing words.'),
  (29, '📖 Because your stories are my favorite to listen to.'),
  (30, '🧿 Because you protect what you love—with care.'),
  (31, '🌙 Because you’re soft and powerful at once.'),
  (32, '🏡 Because you feel like home.'),
  (33, '🧩 Because you understand me in pieces and still love the whole.'),
  (34, '🪄 Because you make ordinary moments feel magical.'),
  (35, '🥰 Because you look cute doing literally anything.'),
  (36, '🫠 Because you make me miss you even when you’re right there.'),
  (37, '🧵 Because you connect hearts, not just conversations.'),
  (38, '🧺 Because you take care in your own quiet ways.'),
  (39, '🎧 Because you listen like it matters.'),
  (40, '🧃 Because you’re sweet without trying.'),
  (41, '🧊 Because you stay calm when things get messy.'),
  (42, '🧨 Because you have spark.'),
  (43, '🌻 Because you turn toward the light—again and again.'),
  (44, '🪶 Because you’re gentle with people’s feelings.'),
  (45, '🧸 Because you deserve to be loved gently.'),
  (46, '🧠 Because you’re smart in a way that feels effortless.'),
  (47, '🫶 Because you show love through actions.'),
  (48, '🧁 Because you make happiness feel simple.'),
  (49, '🪞 Because you reflect the best in people.'),
  (50, '💞 Because loving you feels natural.'),
  (51, '🗺️ Because you make adventures feel safe.'),
  (52, '🧿 Because you notice what others overlook.'),
  (53, '🧷 Because you hold things together when they matter.'),
  (54, '🧡 Because your love is warm.'),
  (55, '🌺 Because you bloom in your own time.'),
  (56, '🫧 Because you bring softness into sharp days.'),
  (57, '🕊️ Because you forgive with grace.'),
  (58, '🪄 Because you make me believe in good things again.'),
  (59, '🧿 Because you protect your peace—and teach me to protect mine.'),
  (60, '💌 Because I love writing you love notes.'),
  (61, '🍓 Because you’re sweet and real.'),
  (62, '🌙 Because you’re my favorite calm.'),
  (63, '🪐 Because you’re my favorite universe.'),
  (64, '🧸 Because you make me want to be soft too.'),
  (65, '🧠 Because you challenge me in the best way.'),
  (66, '🌸 Because you’re beautiful, inside and out.'),
  (67, '🫶 Because you never make love feel like a competition.'),
  (68, '🎀 Because you’re thoughtful. Always.'),
  (69, '✨ Because you shine without asking permission.'),
  (70, '🕯️ Because you’re steady when I need steady.'),
  (71, '🌷 Because you’re delicate and strong.'),
  (72, '💗 Because you’re you—and that’s my favorite.'),
  (73, '🪞 Because you help me love myself more.'),
  (74, '🧁 Because you deserve sweetness, always.'),
  (75, '🫧 Because you make silence feel comfortable.'),
  (76, '🌙 Because you feel like peace at night.'),
  (77, '☀️ Because you feel like hope in the morning.'),
  (78, '🫶 Because you love in ways that heal.'),
  (79, '🪄 Because you make me fall for you again and again.'),
  (80, '💫 Because you’re my favorite kind of destiny.'),
  (81, '🧠 Because your mind is a place I love to visit.'),
  (82, '🧸 Because you deserve softness every day.'),
  (83, '🫶 Because you’re loyal with your whole heart.'),
  (84, '🌸 Because you’re gentle and brave.'),
  (85, '✨ Because you make love feel like light.'),
  (86, '🕯️ Because you’re consistent. That’s rare.'),
  (87, '🫧 Because you bring calm to my chaos.'),
  (88, '🪞 Because you see me. Really see me.'),
  (89, '💌 Because I love choosing you.'),
  (90, '🧁 Because you make life taste sweeter.'),
  (91, '🌙 Because you’re my favorite thought before sleep.'),
  (92, '☀️ Because you’re my favorite reason to smile.'),
  (93, '🫶 Because you make love feel safe.'),
  (94, '🌷 Because you are worth it. Always.'),
  (95, '✨ Because you’re beautiful in every mood.'),
  (96, '💗 Because you make my heart feel at home.'),
  (97, '🪄 Because you make me believe in “us.”'),
  (98, '💫 Because you’re my forever favorite.'),
  (99, '🫶 Because you’re my best decision.'),
  (100, '💍 Because it’s still you. It will always be you.')
ON CONFLICT (unlock_day)
DO UPDATE SET
  reason_text = EXCLUDED.reason_text;

-- =================
-- Compliments (50)
-- =================
INSERT INTO compliments (compliment_text)
VALUES
  ('💖 You’re effortlessly beautiful, but what I love most is how your heart stays gentle even when life isn’t.'),
  ('🌅 Your smile is my favorite sunrise — it makes everything in me feel warm, safe, and brand new.'),
  ('🫶 You have the kind of heart that makes people feel safe to be themselves, and I’m lucky I get to be close to it.'),
  ('✨ The way you care is rare — you love with intention, patience, and softness, and it makes you unforgettable.'),
  ('🌸 You make kindness look powerful, like strength with a warm voice and steady hands.'),
  ('😍 You’re stunning in every way, but especially in your quiet moments when you’re just… you.'),
  ('😂 Your laugh feels like medicine — it fixes parts of my day you didn’t even touch.'),
  ('🛡️ You’re the definition of soft strength: gentle, but unbreakable where it matters.'),
  ('🎀 You make ordinary days feel special, like love can live in the smallest little details.'),
  ('💫 You’re the kind of person love was made for — warm, real, and deeply worth choosing.'),
  ('🥰 You’re so easy to adore that I catch myself smiling just thinking about you.'),
  ('🧠 You’re thoughtful in ways that truly matter — you notice feelings, not just words.'),
  ('🌷 You’re beautiful inside and out, and the “inside” is the part I fall for over and over.'),
  ('🌙 You make me feel calm just by being near — like my nervous system recognizes you as home.'),
  ('✨ You’re glowing — not just in looks, but in energy, in spirit, in the way you exist.'),
  ('🍯 You have the sweetest energy — the kind that makes people softer around you.'),
  ('🌟 You’re more amazing than you realize, and I wish you could see yourself through my eyes for one minute.'),
  ('💌 You’re my favorite person to think about — my mind goes to you the way hands reach for warmth.'),
  ('🤍 You’re incredibly lovable, and you never have to earn it — you already are.'),
  ('🏡 You make my heart feel at home — not perfect, just safe, wanted, and understood.'),
  ('🦢 You’re graceful in your own way — not performative, just naturally beautiful in how you move through life.'),
  ('🔥 You’re the prettiest kind of chaos — the kind that turns boring days into stories I want to replay.'),
  ('🫧 You’re a whole comfort — like a deep breath when everything else feels too loud.'),
  ('🌠 You’re unforgettable — not because you try, but because you’re real and your presence leaves a mark.'),
  ('🏆 You make me proud — of who you are, of how you try, and of how much love you carry.'),
  ('💞 You’re so special to me that sometimes I don’t even have the right words — just the feeling.'),
  ('☀️ You’re the sweetest part of my day — the moment my mood softens and my heart opens.'),
  ('🧸 You deserve the gentlest love — the kind that never rushes you, never scares you, never makes you doubt yourself.'),
  ('📚 You have a beautiful mind — the way you think, the way you notice, the way you understand is genuinely attractive.'),
  ('🌼 You’re such a good person — not loudly, not for show, just quietly and consistently.'),
  ('🫶 You’re my favorite safe place — the place I want to go when I’m happy and when I’m not.'),
  ('✨ You’re made of light — and even on your hard days, you still shine in the ways that count.'),
  ('😌 You’re charming without trying — you don’t force it, you just are it.'),
  ('💗 You make love feel easy — like I can be myself and still be held with care.'),
  ('🌟 You’re genuinely inspiring — you make me want to grow, not out of pressure, but out of love.'),
  ('🐣 You’re adorable when you’re focused — I love watching you do your thing, even in silence.'),
  ('🍀 You make me feel lucky — like life is kinder because you exist in it.'),
  ('🎨 You’re a masterpiece in progress — and I love every version of you, not just the “finished” one.'),
  ('🌹 You’re the best kind of beautiful: real, human, soft, strong, and honest.'),
  ('🕊️ You’re the reason “soft” feels strong — you prove gentleness can be powerful.'),
  ('🫖 You’re so comforting — like warmth I can hold without fear of losing it.'),
  ('🪄 You’re my favorite kind of magic — the kind that’s quiet, consistent, and real.'),
  ('🌷 You’re lovely, always — not because you’re perfect, but because you’re you.'),
  ('💪 You make me want to be better — not to impress you, but because your love makes me believe I can.'),
  ('🫂 You’re a walking warm hug — the kind that makes everything feel less scary.'),
  ('🎉 You’re my favorite person to celebrate — I want to clap for your wins and hold you through the hard parts.'),
  ('💍 You’re perfect to me in all the important ways — the ways that build a life, not just a moment.'),
  ('✨ You shine even when you don’t try — and that’s how I know it’s real.'),
  ('❤️‍🔥 You’re so loved — more than you realize, more than you doubt, more than you ever have to earn.'),
  ('🌙 You’re everything I didn’t know I needed — and now I can’t imagine my world without you.')
ON CONFLICT (compliment_text)
DO NOTHING;

-- =========
-- Coupons
-- =========
-- Note: redemption state lives in coupon_redemptions.
INSERT INTO coupons (title, description, icon, color)
VALUES
  ('One Movie Night Choice', 'You pick the movie. I’m not allowed to complain.', 'Film', 'text-blue-400'),
  ('15 Minute Massage', 'Redeem this for a shoulder + back massage. Slow, gentle, and all yours.', 'Heart', 'text-rose-400'),
  ('Breakfast in Bed', 'Tell me what you’re craving. I’ll bring it to you like royalty.', 'Coffee', 'text-amber-500'),
  ('Dinner on Me', 'Your favorite place. My treat. Your smile required.', 'Utensils', 'text-emerald-500'),
  ('Blank Check', 'Ask for (almost) anything. One time. No guilt.', 'Star', 'text-purple-400')
ON CONFLICT (title)
DO UPDATE SET
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color;

